using System;
using UnityEngine;
using CloudBuilderLibrary;
using System.Reflection;
using IntegrationTests;

public class GodfatherTests : TestBase {

	[InstanceMethod(typeof(GodfatherTests))]
	public string TestMethodName;

	void Start() {
		// Invoke the method described on the integration test script (TestMethodName)
		var met = GetType().GetMethod(TestMethodName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
		// Test methods have a Clan param (and we do the setup here)
		FindObjectOfType<CloudBuilderGameObject>().GetClan(clan => {
			met.Invoke(this, new object[] { clan });
		});
	}

	[Test("Creates two gamers, with one who generates a godfather code and associates it to the other gamer. Then tests all godfather functionality.")]
	public void ShouldAssociateGodfather(Clan clan) {
		Login2NewUsers(clan, (gamer1, gamer2) => {
			new AsyncOp().Then(next => {
				// P1 generates a code and associates P2 with it
				gamer1.Godfather.GenerateCode(genCode => {
					Assert(genCode.IsSuccessful, "Failed to generate code");
					// Use code
					gamer2.Godfather.UseCode(usedCode2 => {
						Assert(usedCode2.IsSuccessful, "Failed to redeem code");
						next.Return();
					}, genCode.Value);
				});
			})
			.Then(next => {
				gamer2.Godfather.GetGodfather(result => {
					Assert(result.IsSuccessful, "Failed to get godfather");
					Assert(result.Value.GamerId == gamer1.GamerId, "P1 should be godfather");
					next.Return();
				});
			})
			.Then(next => {
				gamer1.Godfather.GetGodchildren(result => {
					Assert(result.IsSuccessful, "Failed to get godchildren");
					Assert(result.Value.Count == 1, "Should have only one godchildren");
					Assert(result.Value[0].GamerId == gamer2.GamerId, "P2 should be godchildren");
					next.Return();
				});
			})
			.Then(() => CompleteTest()).Return();
		});
	}

	[Test("Creates an user who tries to redeem a code generated by himself.")]
	public void ShouldNotAssociateGodfatherWithHimself(Clan clan) {
		LoginNewUser(clan, gamer => {
			gamer.Godfather.GenerateCode(genCode => {
				Assert(genCode.IsSuccessful, "Failed to generate code");

				// Should fail to godfather himself
				gamer.Godfather.UseCode(usedCode => {
					Assert(!usedCode.IsSuccessful, "Should fail to use code on himself");
					Assert(usedCode.HttpStatusCode == 400, "Expected HTTP 400");
					Assert(usedCode.ServerData["name"] == "cantBeSelfGodchild", "Expected cantBeSelfGodchild");
					CompleteTest();
				}, genCode.Value);
			});
		});
	}

	#region Private
	private string RandomBoardName() {
		return "board-" + Guid.NewGuid().ToString();
	}
	#endregion
}
