using System;
using System.Collections.Generic;

namespace CotcSdk
{
	/// @ingroup gamer_classes
	/// <summary>Godfather (code) related functions. You may also want to subscribe to events (see #CotcSdk.GamerGodfather.OnGotGodchild).</summary>
	public class GamerGodfather {

		/// <summary>Event triggered when someone adds this gamer as a friend or changes his friendship status.</summary>
		public event Action<GotGodchildEvent> OnGotGodchild {
			add { onGotGodchild += value; CheckEventLoopNeeded(); }
			remove { onGotGodchild -= value; CheckEventLoopNeeded(); }
		}

		/// <summary>
		/// Changes the domain affected by the next operations.
		/// You should typically use it this way: `gamer.Godfather.Domain("private").Associate(...);`
		/// </summary>
		/// <param name="domain">Domain on which to scope the next operations.</param>
		/// <returns>This object for operation chaining.</returns>
		public GamerGodfather Domain(string domain) {
			this.domain = domain;
			return this;
		}

		/// <summary>
		/// Clears all event handlers subscribed, ensuring that a match object can be dismissed without causing further
		/// actions in the background.
		/// </summary>
		public void DiscardEventHandlers() {
			foreach (Action<GotGodchildEvent> e in onGotGodchild.GetInvocationList()) onGotGodchild -= e;
			CheckEventLoopNeeded();
		}

		/// <summary>
		/// Method to call in order to generate a temporary code that can be passed to another gamer so he can
		/// add us as a godfather.
		/// 
		/// The domain as specified by the #Domain method is the domain in which the godfather link should be
		/// established. "private" means it's local to this game only.
		///
		/// </summary>
		/// <returns>Promise resolved when the operation has completed. The attached string is the generated code.</returns>
		public Promise<string> GenerateCode() {
			UrlBuilder url = new UrlBuilder("/v2.6/gamer/godfather").Path(domain);
			HttpRequest req = Gamer.MakeHttpRequest(url);
			req.Method = "PUT";
			return Common.RunInTask<string>(req, (response, task) => {
				task.PostResult(response.BodyJson["godfathercode"]);
			});
		}

		/// <summary>This method can be used to retrieve the gamer who have added you as a godfather.</summary>
		/// <returns>Promise resolved when the operation has completed.</returns>
		public Promise<NonpagedList<GamerInfo>> GetGodchildren() {
			UrlBuilder url = new UrlBuilder("/v2.6/gamer/godchildren").Path(domain);
			HttpRequest req = Gamer.MakeHttpRequest(url);
			return Common.RunInTask<NonpagedList<GamerInfo>>(req, (response, task) => {
				var result = new NonpagedList<GamerInfo>(response.BodyJson);
				foreach (Bundle b in response.BodyJson["godchildren"].AsArray()) {
					result.Add(new GamerInfo(b));
				}
				task.PostResult(result);
			});
		}

		/// <summary>This method can be used to retrieve the godfather of the gamer.</summary>
		/// <returns>Promise resolved when the operation has completed.</returns>
		public Promise<GamerInfo> GetGodfather() {
			UrlBuilder url = new UrlBuilder("/v2.6/gamer/godfather").Path(domain);
			HttpRequest req = Gamer.MakeHttpRequest(url);
			return Common.RunInTask<GamerInfo>(req, (response, task) => {
				task.PostResult(new GamerInfo(response.BodyJson["godfather"]));
			});
		}

		/// <summary>Call this to attribute a godfather to the currently logged in user.</summary>
		/// <returns>Promise resolved when the operation has completed.</returns>
		/// <param name="code">Is a string as generated by #GenerateCode.</param>
		/// <param name="rewardTx">A transaction Json rewarding the godfather formed as follows:
		///     { transaction : { "unit" : amount},
		///     description : "reward transaction",
		///     domain : "com.clanoftcloud.text.DOMAIN" }
		///     where description and domain are optional.</param>
		/// <param name="notification">Optional OS notification to be sent to the godfather who generated the code.
		///     The godfather will reveive an event of type 'godchildren' containing the id of the godchildren
		///     and the balance/achievements field if rewarded.</param>
		public Promise<Done> UseCode(string code, Bundle rewardTx = null, PushNotification notification = null) {
			UrlBuilder url = new UrlBuilder("/v2.6/gamer/godfather").Path(domain);
			HttpRequest req = Gamer.MakeHttpRequest(url);
			Bundle config = Bundle.CreateObject();
			config["godfather"] = code;
			config["osn"] = notification != null ? notification.Data : null;
			config["reward"] = rewardTx;
			req.BodyJson = config;
			return Common.RunInTask<Done>(req, (response, task) => {
				task.PostResult(new Done(response.BodyJson));
			});
		}

		#region Private
		internal GamerGodfather(Gamer parent) {
			Gamer = parent;
		}

		private void CheckEventLoopNeeded() {
			if (onGotGodchild != null) {
				// Register if needed
				if (RegisteredEventLoop == null) {
					RegisteredEventLoop = Cotc.GetEventLoopFor(Gamer.GamerId, domain);
					if (RegisteredEventLoop == null) {
						Common.LogWarning("No pop event loop for domain " + domain + ", community events will not work");
					}
					else {
						RegisteredEventLoop.ReceivedEvent += this.ReceivedLoopEvent;
					}
				}
			}
			else if (RegisteredEventLoop != null) {
				// Unregister from event loop
				RegisteredEventLoop.ReceivedEvent -= this.ReceivedLoopEvent;
				RegisteredEventLoop = null;
			}
		}

		private void ReceivedLoopEvent(DomainEventLoop sender, EventLoopArgs e) {
			if (e.Message["type"].AsString() == "godchildren" && onGotGodchild != null) {
				onGotGodchild(new GotGodchildEvent(e.Message));
			}
		}

		private string domain = Common.PrivateDomain;
		private Gamer Gamer;
		private Action<GotGodchildEvent> onGotGodchild;
		private DomainEventLoop RegisteredEventLoop;
		#endregion
	}

	/// <summary>
	/// Event triggered when a godfather code is used. This event is received by the one who originated the code
	/// (godfather). See #CotcSdk.GamerGodfather.GenerateCode.
	/// </summary>
	public class GotGodchildEvent: PropertiesObject {
		/// <summary>Gamer who accepted the godfather request.</summary>
		public GamerInfo Gamer;
		/// <summary>Reward transaction executed if any.</summary>
		public Bundle Reward;

		public GotGodchildEvent(Bundle serverData) : base(serverData) {
			Gamer = new GamerInfo(serverData["event"]["godchildren"]);
			Reward = serverData["reward"];
		}
	}
}
