// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace CloudBuilderLibrary
{
	public class UnityLogger: ILogger
	{
		private static readonly UnityLogger instance = new UnityLogger();
		
		private UnityLogger() {}
		
		public static UnityLogger Instance {
			get { return instance; }
		}

		#region ILogger implementation
		void ILogger.Log(LogLevel level, string text)
		{
			Debug.Log(text);
		}
		#endregion
	}
}

