// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using LitJson;
using UnityEngine;

namespace CloudBuilderLibrary
{
	public class UnitySystemFunctions: ISystemFunctions
	{
		#region ISystemFunctions implementation
		JsonData ISystemFunctions.CollectDeviceInformation ()
		{
			JsonData result = new JsonData();
			result["model"] = SystemInfo.deviceModel;
			result["version"] = CloudBuilder.Version;
			result["osname"] = SystemInfo.operatingSystem;
			result["name"] = SystemInfo.deviceName;
			return result;
		}
		#endregion
	}
}

