// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using LitJson;

namespace CloudBuilderLibrary {

	public class HttpRequest {
		public string BodyString {
			get { return body; }
			set { body = value; }
		}
		public JsonData BodyJson {
			set { body = JsonMapper.ToJson(value); }
		}
		public Action<HttpResponse, Exception> Callback;
		public bool HasBody {
			get { return body != null; }
		}
		public Dictionary<String, String> Headers = new Dictionary<string, string>();
		/**
		 * When not set (null), uses GET if no body is provided, or POST otherwise.
		 */
		public string Method;
		public string Url;
		public int TimeoutMillisec;

		private string body;
	}

	public class HttpResponse {
		public string BodyString {
			get { return body; }
			set { body = value; }
		}
		public bool HasBody {
			get { return body != null; }
		}
		public Dictionary<String, String> Headers = new Dictionary<string, string>();
		public string OriginalUrl;
		public int StatusCode;
		
		private string body;
	}

}

